name: 'Create Discussion Comment'
description: 'Create Comments on Exsiting GitHub Discussions using GitHub Actions'
author: 'Wesley Scholl'
icon: command
runs:
  using: 'docker'
  image: 'Dockerfile'
  
