name: 'Create Discussion Comment'
description: 'Create Comments on Exsiting GitHub Discussions using GitHub Actions'
author: 'Wesley Scholl'

runs:
  using: 'node16'
  main: 'dist/index.js'


inputs:
  token:
    description: 'GitHub PAT token, defaults to secrets.GITHUB_TOKEN'
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  graphql-url:
    description: 'GitHub GraphQL Endpoint URL'
    required: false
    default: https://api.github.com/graphql
  body:
    description: 'Comment Body String'
    required: false
    default: 'Default Comment Body String'
  discussion-id:
    description: 'Discussion Topic ID - String'
    required: true
  gql-client-mutation-id:
    description: 'A unique numeric string required by GraphQL for mutations'
    required: false
    default: '1234'


branding:
  icon: 'activity'
  color: 'green'

