name: Comment

on:
  workflow_dispatch:

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: '${{ secrets.TEST_TOKEN }}'
          graphql-url: https://google.com
          body: "This is a test comment!"
          discussion-id: '2j3j47f8g6f5dfk'
          gql-client-mutation-id: '8888'
    