name: Comment

on:
  workflow_dispatch:

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: 'TEST_TOKEN'
          graphql-url: 'https://api.github.com/graphql'
          body: "This is a test comment!"
          discussion-id: 'D_kwDOKMfoY84AVVQ6'
          gql-client-mutation-id: '8888'
    