name: Create Comment
on: [workflow_dispatch]
jobs:
  comment:
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Run create-discussion-comment
      uses: wesleyscholl/create-discussion-comment@v1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create-comment
      with:
        discussion-id: 'D_kwDOKEe7W84AVXOO'
        client-mutation-id: '8888'
        token: ${{ GITHUB_TOKEN }}
        body: "This is a test comment from a GitHub action"

    - name: echo output from create-discussion-comment
      run: |
        echo ${{ steps.create-comment.outputs.commentid }}