name: Create Comment
on: [workflow_dispatch]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Run create-discussion-comment
      uses: wesleyscholl/create-discussion-comment@v1.0.6
      id: create-comment
      with:
        discussion-id: 'D_kwDOKMfoY84AVVQ6'

    - name: echo output from create-discussion-comment
      run: |
        echo ${{ steps.create-comment.outputs.commentid }}