on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test-action
      uses: ./.github/actions/action
      with:
        args: -X POST https://httpbin.org/post
        
